logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: hmall
    username: waterside
    password: 123
    connection-timeout: 1s #设置MQ的超时时间
    template:
      retry:
        enabled: true  #开启超时重试机制
        initial-interval: 1000ms   #失败后的初始等待时间
        multiplier: 2    #失败后下次等待时长的倍数
        max-attempts: 3
    publisher-confirm-type: correlated #none 关闭confirm机制，simple 同步等待消息返回， correlated 返回确认进行异步回调。
    publisher-returns: true #消息未成功路由时返回，如果成功了则不返回。